components:
  frontendProxy:
    ingress:
      enabled: true
      annotations: {}
      ingressClassName: nginx
      hosts:
        - host: frontend-proxy-oteldemo.example.com
          paths:
            - path: /
              pathType: Prefix
              port: 8080
  loadgenerator: # added as separate ingress since under frontendproxy, UI has problems
    ingress:
      enabled: true
      annotations: {}
      ingressClassName: nginx
      hosts:
        - host: load-generator-oteldemo.example.com
          paths:
            - path: /
              pathType: Prefix
              port: 8089

opentelemetry-collector:
  config:
    processors:
      batch:
        send_batch_size: 10000
      probabilistic_sampler:
        hash_seed: 22
        sampling_percentage: 25
    service:
      pipelines:
        traces:
          processors:
          - k8sattributes
          - memory_limiter
          - probabilistic_sampler
          - resource
          - batch
    exporters:
      debug:
        verbosity: normal